version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        restart: always
        environment: 
             - SECRET_KEY
             - POSTGRES_USER
             - POSTGRES_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
        volumes: 
            - ./database:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    app:
        build:
            context: ./app/
        volumes: 
            - ./app:/app
        ports:
            - '80:80'
        restart: always
        depends_on: 
            - 'postgres'
        environment: 
             - SECRET_KEY
             - POSTGRES_RW_USER
             - POSTGRES_RW_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
    mailer:
        build:
            context: ./mailer/
        volumes: 
            - ./mailer:/mailer
        restart: always
        depends_on: 
            - 'postgres'
        environment: 
             - SECRET_KEY
             - POSTGRES_RW_USER
             - POSTGRES_RW_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
             - EMAIL_PASS