version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        restart: always
        environment: 
             - SECRET_KEY
             - POSTGRES_USER
             - POSTGRES_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
        volumes: 
            - ./database:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    app:
        build:
            context: ./app/
        volumes: 
            - ./app:/app
        ports:
            - '3000:3000'
        restart: always
        depends_on: 
            - 'postgres'
        environment: 
             - SECRET_KEY
             - POSTGRES_RW_USER
             - POSTGRES_RW_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
             - STRIPE_DOMAIN
             - STRIPE_WEBHOOK_SUB_SECRET
             - EMAIL_PASS
             - STRIPE_API_KEY
    mailer:
        build:
            context: ./mailer/
        volumes: 
            - ./mailer:/mailer
        restart: always
        depends_on: 
            - 'postgres'
        environment: 
             - SECRET_KEY
             - POSTGRES_RW_USER
             - POSTGRES_RW_PASSWORD
             - POSTGRES_DB
             - POSTGRES_PORT
             - POSTGRES_DATABASE
             - POSTGRES_HOST
             - EMAIL_PASS
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"